/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as AuthenticatedStudentsIndexRouteImport } from './routes/_authenticated/students/index'
import { Route as AuthenticatedStudentsStudentIdRouteRouteImport } from './routes/_authenticated/students/$studentId/route'
import { Route as AuthenticatedStudentsStudentIdIndexRouteImport } from './routes/_authenticated/students/$studentId/index'
import { Route as AuthenticatedStudentsStudentIdGamesGameIdRouteImport } from './routes/_authenticated/students/$studentId/games/$gameId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudentsIndexRoute =
  AuthenticatedStudentsIndexRouteImport.update({
    id: '/students/',
    path: '/students/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentsStudentIdRouteRoute =
  AuthenticatedStudentsStudentIdRouteRouteImport.update({
    id: '/students/$studentId',
    path: '/students/$studentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentsStudentIdIndexRoute =
  AuthenticatedStudentsStudentIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedStudentsStudentIdRouteRoute,
  } as any)
const AuthenticatedStudentsStudentIdGamesGameIdRoute =
  AuthenticatedStudentsStudentIdGamesGameIdRouteImport.update({
    id: '/games/$gameId',
    path: '/games/$gameId',
    getParentRoute: () => AuthenticatedStudentsStudentIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/students/$studentId': typeof AuthenticatedStudentsStudentIdRouteRouteWithChildren
  '/students/': typeof AuthenticatedStudentsIndexRoute
  '/students/$studentId/': typeof AuthenticatedStudentsStudentIdIndexRoute
  '/students/$studentId/games/$gameId': typeof AuthenticatedStudentsStudentIdGamesGameIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/students': typeof AuthenticatedStudentsIndexRoute
  '/students/$studentId': typeof AuthenticatedStudentsStudentIdIndexRoute
  '/students/$studentId/games/$gameId': typeof AuthenticatedStudentsStudentIdGamesGameIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/students/$studentId': typeof AuthenticatedStudentsStudentIdRouteRouteWithChildren
  '/_authenticated/students/': typeof AuthenticatedStudentsIndexRoute
  '/_authenticated/students/$studentId/': typeof AuthenticatedStudentsStudentIdIndexRoute
  '/_authenticated/students/$studentId/games/$gameId': typeof AuthenticatedStudentsStudentIdGamesGameIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/activity'
    | '/students/$studentId'
    | '/students/'
    | '/students/$studentId/'
    | '/students/$studentId/games/$gameId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/activity'
    | '/students'
    | '/students/$studentId'
    | '/students/$studentId/games/$gameId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/_authenticated/activity'
    | '/_authenticated/students/$studentId'
    | '/_authenticated/students/'
    | '/_authenticated/students/$studentId/'
    | '/_authenticated/students/$studentId/games/$gameId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students/': {
      id: '/_authenticated/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof AuthenticatedStudentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students/$studentId': {
      id: '/_authenticated/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof AuthenticatedStudentsStudentIdRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students/$studentId/': {
      id: '/_authenticated/students/$studentId/'
      path: '/'
      fullPath: '/students/$studentId/'
      preLoaderRoute: typeof AuthenticatedStudentsStudentIdIndexRouteImport
      parentRoute: typeof AuthenticatedStudentsStudentIdRouteRoute
    }
    '/_authenticated/students/$studentId/games/$gameId': {
      id: '/_authenticated/students/$studentId/games/$gameId'
      path: '/games/$gameId'
      fullPath: '/students/$studentId/games/$gameId'
      preLoaderRoute: typeof AuthenticatedStudentsStudentIdGamesGameIdRouteImport
      parentRoute: typeof AuthenticatedStudentsStudentIdRouteRoute
    }
  }
}

interface AuthenticatedStudentsStudentIdRouteRouteChildren {
  AuthenticatedStudentsStudentIdIndexRoute: typeof AuthenticatedStudentsStudentIdIndexRoute
  AuthenticatedStudentsStudentIdGamesGameIdRoute: typeof AuthenticatedStudentsStudentIdGamesGameIdRoute
}

const AuthenticatedStudentsStudentIdRouteRouteChildren: AuthenticatedStudentsStudentIdRouteRouteChildren =
  {
    AuthenticatedStudentsStudentIdIndexRoute:
      AuthenticatedStudentsStudentIdIndexRoute,
    AuthenticatedStudentsStudentIdGamesGameIdRoute:
      AuthenticatedStudentsStudentIdGamesGameIdRoute,
  }

const AuthenticatedStudentsStudentIdRouteRouteWithChildren =
  AuthenticatedStudentsStudentIdRouteRoute._addFileChildren(
    AuthenticatedStudentsStudentIdRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedStudentsStudentIdRouteRoute: typeof AuthenticatedStudentsStudentIdRouteRouteWithChildren
  AuthenticatedStudentsIndexRoute: typeof AuthenticatedStudentsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedStudentsStudentIdRouteRoute:
    AuthenticatedStudentsStudentIdRouteRouteWithChildren,
  AuthenticatedStudentsIndexRoute: AuthenticatedStudentsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
