/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/students": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["StudentsController_list"];
        put?: never;
        post: operations["StudentsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/students/{studentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["StudentsController_getOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["StudentsController_update"];
        trace?: never;
    };
    "/api/students/{studentId}/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["StudentsController_getOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/students/{studentId}/analysis-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["StudentsController_getAnalysisProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/students/{studentId}/performance-trend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["StudentsController_getPerformanceTrend"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/students/{studentId}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["StudentsController_setArchiveState"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/students/{studentId}/external-accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ExternalAccountsController_list"];
        put?: never;
        post: operations["ExternalAccountsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/students/{studentId}/external-accounts/{externalAccountId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["ExternalAccountsController_remove"];
        options?: never;
        head?: never;
        patch: operations["ExternalAccountsController_update"];
        trace?: never;
    };
    "/api/students/{studentId}/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GamesController_listStudentGames"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{gameId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GamesController_getOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{gameId}/pgn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GamesController_getPgn"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AnalysisJobsController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis/jobs/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AnalysisJobsController_getStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis/jobs/{jobId}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AnalysisJobsController_retry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AnalysisController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis/{analysisId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AnalysisController_getOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/students/{studentId}/imports/pgn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ImportsController_importPgn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis/{analysisId}/reports/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ReportsController_requestGeneration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ReportsController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/{reportId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ReportsController_getOne"];
        put?: never;
        post?: never;
        delete: operations["ReportsController_remove"];
        options?: never;
        head?: never;
        patch: operations["ReportsController_update"];
        trace?: never;
    };
    "/api/analysis/{analysisId}/homework/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["HomeworkController_requestGeneration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/homework": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HomeworkController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/homework/{homeworkId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HomeworkController_getOne"];
        put?: never;
        post?: never;
        delete: operations["HomeworkController_remove"];
        options?: never;
        head?: never;
        patch: operations["HomeworkController_update"];
        trace?: never;
    };
    "/api/students/{studentId}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProgressController_getLatest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/students/{studentId}/progress/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ProgressController_requestGeneration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterDto: {
            /** @example coach.alex.petrov@example.com */
            email: string;
            /** @example StrongPass123 */
            password: string;
            /** @example Alex Petrov */
            displayName: string;
        };
        LoginDto: {
            /** @example coach.alex.petrov@example.com */
            email: string;
            /** @example StrongPass123 */
            password: string;
        };
        CoachProfileResponse: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            displayName: string;
        };
        AuthResponse: {
            accessToken: string;
            coach: components["schemas"]["CoachProfileResponse"];
        };
        RefreshAccessTokenResponse: {
            accessToken: string;
        };
        CreateStudentDto: {
            /** @example Maksim Sokolov */
            displayName: string;
            /** @example 2012 */
            birthYear?: number;
            /** @example 1460 */
            rating?: number;
            /** @example Focuses on tactics and rook endgames. */
            notes?: string;
        };
        UpdateStudentDto: {
            /** @example Maksim Sokolov */
            displayName?: string;
            /** @example 2012 */
            birthYear?: number;
            /** @example 1460 */
            rating?: number;
            /** @example Focuses on tactics and rook endgames. */
            notes?: string;
        };
        SetStudentArchiveDto: {
            /** @example true */
            archived: boolean;
        };
        StudentReadResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            coachAccountId: string;
            displayName: string;
            birthYear: number | null;
            rating: number | null;
            notes: string | null;
            /** Format: date-time */
            archivedAt: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        StudentListItemResponse: {
            /** Format: uuid */
            id: string;
            displayName: string;
            birthYear: number | null;
            rating: number | null;
            /** Format: date-time */
            archivedAt: string | null;
            completedAnalysisCount: number;
            /** Format: date-time */
            lastAnalysisAt: string | null;
            /** @enum {string|null} */
            latestAnalysisJobStatus: "PENDING" | "PARSING" | "EXTRACTING_ANNOTATIONS" | "CLASSIFICATION" | "GENERATING_OUTPUT" | "COMPLETED" | "FAILED" | null;
            /** @enum {string|null} */
            mainWeaknessTag: "MISSED_FORK" | "MISSED_PIN" | "MISSED_DOUBLE_ATTACK" | "MISSED_DISCOVERED_ATTACK" | "MISSED_MATE" | "ALLOWED_MATE" | "HANGING_PIECE" | "MISSED_CAPTURE" | "BAD_CAPTURE" | "MISSED_OPPONENT_THREAT" | "OPENED_LINE" | "UNKNOWN_TACTICAL_ERROR" | "KING_SAFETY" | "DELAYED_CASTLING" | "POOR_DEVELOPMENT" | "EARLY_QUEEN" | "BAD_TRADE" | "POOR_CONVERSION" | "OPENING_STRATEGY" | "PAWN_STRUCTURE" | "ENDGAME_TECHNIQUE" | "UNKNOWN_STRATEGIC_ERROR" | "TIME_MANAGEMENT" | "CALCULATION_DEPTH" | "TUNNEL_VISION" | "MATERIAL_GREED" | "LOW_BOARD_AWARENESS" | "INSUFFICIENT_ANNOTATION_DATA" | "REDUCED_CONFIDENCE" | null;
        };
        StudentListResponse: {
            items: components["schemas"]["StudentListItemResponse"][];
            total: number;
            page: number;
            limit: number;
            totalPages: number;
        };
        StudentOverviewStudentResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            coachAccountId: string;
            displayName: string;
            birthYear: number | null;
            rating: number | null;
            notes: string | null;
            /** Format: date-time */
            archivedAt: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ExternalAccountResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            studentId: string;
            /** @enum {string} */
            platform: "LICHESS" | "CHESS_COM";
            username: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        StudentOverviewStatsResponse: {
            gameCount: number;
            analysisCount: number;
            reportCount: number;
            homeworkCount: number;
        };
        LatestProgressReferenceResponse: {
            /** Format: uuid */
            id: string;
            analysisCount: number;
            /** Format: date-time */
            createdAt: string;
        };
        RecentGameResponse: {
            /** Format: uuid */
            id: string;
            sourceLabel: string | null;
            /** @enum {string} */
            studentColor: "WHITE" | "BLACK";
            event: string | null;
            site: string | null;
            whitePlayerName: string | null;
            blackPlayerName: string | null;
            openingHeader: string | null;
            ecoCode: string | null;
            rawResult: string | null;
            /** @enum {string} */
            derivedResult: "WIN" | "LOSS" | "DRAW" | "UNKNOWN";
            plyCount: number | null;
            /** Format: date-time */
            importedAt: string;
            /** @enum {string|null} */
            latestAnalysisJobStatus: "PENDING" | "PARSING" | "EXTRACTING_ANNOTATIONS" | "CLASSIFICATION" | "GENERATING_OUTPUT" | "COMPLETED" | "FAILED" | null;
            /** Format: uuid */
            latestAnalysisJobId: string | null;
            /** Format: uuid */
            latestAnalysisId: string | null;
        };
        RecentAnalysisResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            analysisJobId: string;
            /** Format: uuid */
            gameId: string;
            /** @enum {string|null} */
            mainWeaknessTag: "MISSED_FORK" | "MISSED_PIN" | "MISSED_DOUBLE_ATTACK" | "MISSED_DISCOVERED_ATTACK" | "MISSED_MATE" | "ALLOWED_MATE" | "HANGING_PIECE" | "MISSED_CAPTURE" | "BAD_CAPTURE" | "MISSED_OPPONENT_THREAT" | "OPENED_LINE" | "UNKNOWN_TACTICAL_ERROR" | "KING_SAFETY" | "DELAYED_CASTLING" | "POOR_DEVELOPMENT" | "EARLY_QUEEN" | "BAD_TRADE" | "POOR_CONVERSION" | "OPENING_STRATEGY" | "PAWN_STRUCTURE" | "ENDGAME_TECHNIQUE" | "UNKNOWN_STRATEGIC_ERROR" | "TIME_MANAGEMENT" | "CALCULATION_DEPTH" | "TUNNEL_VISION" | "MATERIAL_GREED" | "LOW_BOARD_AWARENESS" | "INSUFFICIENT_ANNOTATION_DATA" | "REDUCED_CONFIDENCE" | null;
            recommendedLessonTitle: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        RecentReportResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            analysisId: string;
            title: string;
            /** @enum {string} */
            audience: "COACH" | "PARENT";
            /** Format: date-time */
            createdAt: string;
        };
        RecentHomeworkResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            analysisId: string;
            title: string;
            /** Format: date-time */
            createdAt: string;
        };
        StudentOverviewResponse: {
            student: components["schemas"]["StudentOverviewStudentResponse"];
            externalAccounts: components["schemas"]["ExternalAccountResponse"][];
            stats: components["schemas"]["StudentOverviewStatsResponse"];
            latestProgress: components["schemas"]["LatestProgressReferenceResponse"] | null;
            recentGames: components["schemas"]["RecentGameResponse"][];
            recentAnalyses: components["schemas"]["RecentAnalysisResponse"][];
            recentReports: components["schemas"]["RecentReportResponse"][];
            recentHomework: components["schemas"]["RecentHomeworkResponse"][];
        };
        WeaknessTagCountResponse: {
            /** @enum {string} */
            tag: "MISSED_FORK" | "MISSED_PIN" | "MISSED_DOUBLE_ATTACK" | "MISSED_DISCOVERED_ATTACK" | "MISSED_MATE" | "ALLOWED_MATE" | "HANGING_PIECE" | "MISSED_CAPTURE" | "BAD_CAPTURE" | "MISSED_OPPONENT_THREAT" | "OPENED_LINE" | "UNKNOWN_TACTICAL_ERROR" | "KING_SAFETY" | "DELAYED_CASTLING" | "POOR_DEVELOPMENT" | "EARLY_QUEEN" | "BAD_TRADE" | "POOR_CONVERSION" | "OPENING_STRATEGY" | "PAWN_STRUCTURE" | "ENDGAME_TECHNIQUE" | "UNKNOWN_STRATEGIC_ERROR" | "TIME_MANAGEMENT" | "CALCULATION_DEPTH" | "TUNNEL_VISION" | "MATERIAL_GREED" | "LOW_BOARD_AWARENESS" | "INSUFFICIENT_ANNOTATION_DATA" | "REDUCED_CONFIDENCE";
            count: number;
        };
        SeverityCountResponse: {
            /** @enum {string} */
            severity: "INACCURACY" | "MISTAKE" | "BLUNDER" | "MATE" | "UNKNOWN";
            count: number;
        };
        SampleMistakeResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            analysisId: string;
            /** Format: uuid */
            gameId: string;
            /** @enum {string} */
            severity: "INACCURACY" | "MISTAKE" | "BLUNDER" | "MATE" | "UNKNOWN";
            category: string;
            explanation: string;
            suggestedFix: string | null;
        };
        StudentAnalysisProfileResponse: {
            analysisCountUsed: number;
            /** @enum {string|null} */
            mainWeaknessTag: "MISSED_FORK" | "MISSED_PIN" | "MISSED_DOUBLE_ATTACK" | "MISSED_DISCOVERED_ATTACK" | "MISSED_MATE" | "ALLOWED_MATE" | "HANGING_PIECE" | "MISSED_CAPTURE" | "BAD_CAPTURE" | "MISSED_OPPONENT_THREAT" | "OPENED_LINE" | "UNKNOWN_TACTICAL_ERROR" | "KING_SAFETY" | "DELAYED_CASTLING" | "POOR_DEVELOPMENT" | "EARLY_QUEEN" | "BAD_TRADE" | "POOR_CONVERSION" | "OPENING_STRATEGY" | "PAWN_STRUCTURE" | "ENDGAME_TECHNIQUE" | "UNKNOWN_STRATEGIC_ERROR" | "TIME_MANAGEMENT" | "CALCULATION_DEPTH" | "TUNNEL_VISION" | "MATERIAL_GREED" | "LOW_BOARD_AWARENESS" | "INSUFFICIENT_ANNOTATION_DATA" | "REDUCED_CONFIDENCE" | null;
            secondaryWeaknessTags: ("MISSED_FORK" | "MISSED_PIN" | "MISSED_DOUBLE_ATTACK" | "MISSED_DISCOVERED_ATTACK" | "MISSED_MATE" | "ALLOWED_MATE" | "HANGING_PIECE" | "MISSED_CAPTURE" | "BAD_CAPTURE" | "MISSED_OPPONENT_THREAT" | "OPENED_LINE" | "UNKNOWN_TACTICAL_ERROR" | "KING_SAFETY" | "DELAYED_CASTLING" | "POOR_DEVELOPMENT" | "EARLY_QUEEN" | "BAD_TRADE" | "POOR_CONVERSION" | "OPENING_STRATEGY" | "PAWN_STRUCTURE" | "ENDGAME_TECHNIQUE" | "UNKNOWN_STRATEGIC_ERROR" | "TIME_MANAGEMENT" | "CALCULATION_DEPTH" | "TUNNEL_VISION" | "MATERIAL_GREED" | "LOW_BOARD_AWARENESS" | "INSUFFICIENT_ANNOTATION_DATA" | "REDUCED_CONFIDENCE")[];
            tagCounts: components["schemas"]["WeaknessTagCountResponse"][];
            severityCounts: components["schemas"]["SeverityCountResponse"][];
            sampleMistakes: components["schemas"]["SampleMistakeResponse"][];
            recommendedLessonTitle: string | null;
        };
        PerformanceTrendPointResponse: {
            /** @example 2026-08-13 */
            date: string;
            value: number;
        };
        StudentPerformanceTrendResponse: {
            /** @enum {string} */
            direction: "IMPROVING" | "STABLE" | "DECLINING" | "UNKNOWN";
            primaryMetric: string;
            /** @enum {string} */
            range: "90D";
            points: components["schemas"]["PerformanceTrendPointResponse"][];
        };
        CreateExternalAccountDto: {
            /**
             * @example LICHESS
             * @enum {string}
             */
            platform: "LICHESS" | "CHESS_COM";
            /** @example maksim_sokolov_2012 */
            username: string;
        };
        UpdateExternalAccountDto: {
            /**
             * @example LICHESS
             * @enum {string}
             */
            platform: "LICHESS" | "CHESS_COM";
            /** @example maksim_sokolov_2012 */
            username: string;
        };
        AnalysisCriticalMomentResponse: {
            /** Format: uuid */
            id: string;
            analysisId: string;
            ply: number;
            fullMoveNumber: number;
            moveNumber: string;
            /** @enum {string} */
            moveColor: "WHITE" | "BLACK";
            san: string;
            lan: string | null;
            uci: string | null;
            beforeFen: string;
            afterFen: string;
            bestMove: string | null;
            bestVariation: {
                [key: string]: unknown;
            }[];
            nags: {
                [key: string]: unknown;
            }[];
            comments: {
                [key: string]: unknown;
            }[];
            evaluationBefore: {
                [key: string]: unknown;
            } | null;
            evaluationAfter: {
                [key: string]: unknown;
            } | null;
            /** @enum {string} */
            severity: "INACCURACY" | "MISTAKE" | "BLUNDER" | "MATE" | "UNKNOWN";
            sourceEvidence: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        AnalysisMistakeResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            analysisId: string;
            /** Format: uuid */
            criticalMomentId: string | null;
            /** @enum {string} */
            severity: "INACCURACY" | "MISTAKE" | "BLUNDER" | "MATE" | "UNKNOWN";
            category: string;
            explanation: string;
            suggestedFix: string | null;
            sourceEvidence: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        AnalysisDetailsResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            analysisJobId: string;
            /** Format: uuid */
            gameId: string;
            /** Format: uuid */
            studentId: string;
            /** @enum {string} */
            confidenceLevel: "HIGH" | "MEDIUM" | "LOW";
            /** @enum {string} */
            annotationCoverage: "NONE" | "PARTIAL" | "FULL";
            reducedConfidenceWarning: string | null;
            overallDiagnosis: string;
            openingName: string | null;
            /** @enum {string} */
            result: "WIN" | "LOSS" | "DRAW" | "UNKNOWN";
            /** @enum {string|null} */
            mainWeaknessTag: "MISSED_FORK" | "MISSED_PIN" | "MISSED_DOUBLE_ATTACK" | "MISSED_DISCOVERED_ATTACK" | "MISSED_MATE" | "ALLOWED_MATE" | "HANGING_PIECE" | "MISSED_CAPTURE" | "BAD_CAPTURE" | "MISSED_OPPONENT_THREAT" | "OPENED_LINE" | "UNKNOWN_TACTICAL_ERROR" | "KING_SAFETY" | "DELAYED_CASTLING" | "POOR_DEVELOPMENT" | "EARLY_QUEEN" | "BAD_TRADE" | "POOR_CONVERSION" | "OPENING_STRATEGY" | "PAWN_STRUCTURE" | "ENDGAME_TECHNIQUE" | "UNKNOWN_STRATEGIC_ERROR" | "TIME_MANAGEMENT" | "CALCULATION_DEPTH" | "TUNNEL_VISION" | "MATERIAL_GREED" | "LOW_BOARD_AWARENESS" | "INSUFFICIENT_ANNOTATION_DATA" | "REDUCED_CONFIDENCE" | null;
            secondaryWeaknessTags: ("MISSED_FORK" | "MISSED_PIN" | "MISSED_DOUBLE_ATTACK" | "MISSED_DISCOVERED_ATTACK" | "MISSED_MATE" | "ALLOWED_MATE" | "HANGING_PIECE" | "MISSED_CAPTURE" | "BAD_CAPTURE" | "MISSED_OPPONENT_THREAT" | "OPENED_LINE" | "UNKNOWN_TACTICAL_ERROR" | "KING_SAFETY" | "DELAYED_CASTLING" | "POOR_DEVELOPMENT" | "EARLY_QUEEN" | "BAD_TRADE" | "POOR_CONVERSION" | "OPENING_STRATEGY" | "PAWN_STRUCTURE" | "ENDGAME_TECHNIQUE" | "UNKNOWN_STRATEGIC_ERROR" | "TIME_MANAGEMENT" | "CALCULATION_DEPTH" | "TUNNEL_VISION" | "MATERIAL_GREED" | "LOW_BOARD_AWARENESS" | "INSUFFICIENT_ANNOTATION_DATA" | "REDUCED_CONFIDENCE")[];
            recommendedLessonTitle: string | null;
            recommendedLessonWhy: string | null;
            recommendedFocusPoints: string[];
            criticalMoments: components["schemas"]["AnalysisCriticalMomentResponse"][];
            mistakes: components["schemas"]["AnalysisMistakeResponse"][];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ImportPgnDto: {
            /**
             * @example WHITE
             * @enum {string}
             */
            studentColor: "WHITE" | "BLACK";
            /** @example Lichess Study export */
            sourceLabel?: string;
            /**
             * @example [Event "Training Game"]
             *     [Site "Lichess"]
             *     [Date "2026.07.25"]
             *     [Round "?"]
             *     [White "Student"]
             *     [Black "Opponent"]
             *     [Result "1-0"]
             *
             *     1. e4 { [%eval 0.3] Good central control. } e5 { [%eval 0.1] } 2. Nf3 { [%eval 0.5] } Nc6 { [%eval 0.2] } 3. Bb5 { [%eval 0.9] } a6 { [%eval 0.4] } 1-0
             */
            rawPgn: string;
        };
        ReportGenerationRequestDto: {
            /**
             * @example COACH
             * @enum {string}
             */
            audience: "COACH" | "PARENT";
        };
        ReportUpdateDto: {
            /** @example Coach report: Italian Game review */
            title?: string;
            /**
             * @example {
             *       "summary": "Middlegame planning improved, but tactical checks were rushed.",
             *       "highlights": [
             *         "Better opening recall",
             *         "Missed forcing continuation on move 18"
             *       ],
             *       "lessonFocus": [
             *         "Candidate move discipline"
             *       ],
             *       "nextSteps": [
             *         "Review forcing-move checklist"
             *       ]
             *     }
             */
            content?: Record<string, never>;
        };
        HomeworkUpdateDto: {
            /** @example Homework: candidate move discipline */
            title?: string;
            /**
             * @example {
             *       "overview": "Review the forcing-move checklist before every capture.",
             *       "exercises": [
             *         "Annotate move 18 alternatives",
             *         "Solve 5 fork puzzles"
             *       ],
             *       "focusPoints": [
             *         "Checks, captures, threats"
             *       ],
             *       "notes": [
             *         "Discuss move-order discipline in next lesson"
             *       ]
             *     }
             */
            content?: Record<string, never>;
        };
        ProgressSnapshotResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            studentId: string;
            analysisCount: number;
            summary: {
                [key: string]: unknown;
            };
            promptVersion: string;
            model: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ProgressReadResponse: {
            /** @enum {string} */
            status: "ready" | "not-enough-data";
            requiredAnalysisCount: number;
            availableAnalysisCount: number;
            snapshot: components["schemas"]["ProgressSnapshotResponse"] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshAccessTokenResponse"];
                };
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Refresh session revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoachProfileResponse"];
                };
            };
        };
    };
    StudentsController_list: {
        parameters: {
            query?: {
                /** @description Case-insensitive search by student display name. */
                search?: string;
                statuses?: ("active" | "archived")[];
                sort?: "rating" | "completedAnalysisCount" | "lastAnalysisAt";
                order?: "asc" | "desc";
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentListResponse"];
                };
            };
        };
    };
    StudentsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateStudentDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentReadResponse"];
                };
            };
        };
    };
    StudentsController_getOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                studentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentReadResponse"];
                };
            };
        };
    };
    StudentsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                studentId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateStudentDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentReadResponse"];
                };
            };
        };
    };
    StudentsController_getOverview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                studentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentOverviewResponse"];
                };
            };
        };
    };
    StudentsController_getAnalysisProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                studentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentAnalysisProfileResponse"];
                };
            };
        };
    };
    StudentsController_getPerformanceTrend: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                studentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentPerformanceTrendResponse"];
                };
            };
        };
    };
    StudentsController_setArchiveState: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                studentId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetStudentArchiveDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentReadResponse"];
                };
            };
        };
    };
    ExternalAccountsController_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                studentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ExternalAccountsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                studentId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateExternalAccountDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ExternalAccountsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                studentId: string;
                externalAccountId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ExternalAccountsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                studentId: string;
                externalAccountId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateExternalAccountDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GamesController_listStudentGames: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string;
                analysisStatus?: "PENDING" | "PARSING" | "EXTRACTING_ANNOTATIONS" | "CLASSIFICATION" | "GENERATING_OUTPUT" | "COMPLETED" | "FAILED";
            };
            header?: never;
            path: {
                studentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GamesController_getOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gameId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GamesController_getPgn: {
        parameters: {
            query?: {
                download?: boolean;
            };
            header?: never;
            path: {
                gameId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AnalysisJobsController_list: {
        parameters: {
            query?: {
                studentId?: string;
                gameId?: string;
                jobType?: "ANALYSIS" | "REPORT_GENERATION" | "HOMEWORK_GENERATION" | "PROGRESS_GENERATION";
                status?: "PENDING" | "PARSING" | "EXTRACTING_ANNOTATIONS" | "CLASSIFICATION" | "GENERATING_OUTPUT" | "COMPLETED" | "FAILED";
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AnalysisJobsController_getStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AnalysisJobsController_retry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AnalysisController_list: {
        parameters: {
            query?: {
                studentId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AnalysisController_getOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysisId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisDetailsResponse"];
                };
            };
        };
    };
    ImportsController_importPgn: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                studentId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportPgnDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReportsController_requestGeneration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysisId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportGenerationRequestDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReportsController_list: {
        parameters: {
            query: {
                studentId: string;
                analysisId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReportsController_getOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reportId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReportsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reportId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReportsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reportId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportUpdateDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HomeworkController_requestGeneration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysisId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HomeworkController_list: {
        parameters: {
            query: {
                studentId: string;
                analysisId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HomeworkController_getOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                homeworkId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HomeworkController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                homeworkId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HomeworkController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                homeworkId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HomeworkUpdateDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProgressController_getLatest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                studentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressReadResponse"];
                };
            };
        };
    };
    ProgressController_requestGeneration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                studentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
